//
//  UserCommandResponse.swift
//  App
//
//  Created by Chris Martin on 4/14/18.
//

import Foundation
import Vapor

final class Reply: SlackResponse {
    
    var text: String
    var replyType: ReplyType
    var attachments: [Attachment]
    
    enum CodingKeys: String, CodingKey {
        case text
        case replyType = "response_type"
        case attachments
    }
    
    init(text: String, replyType: ReplyType = .inChannel, attachments: [Attachment] = []) {
        
        self.text = text
        self.replyType = replyType
        self.attachments = attachments
    }
    
    func future(on container: Container) -> Future<Reply> {
        
        return Future.map(on: container) { self }
    }
}

extension Reply {
    
    static func inspirobot(imageURL: URL) -> Reply {
        
        return Reply(
            text: "Auto-generated by Inspirobot.",
            replyType: .inChannel,
            attachments: [
                Attachment(imageUrl: imageURL)
            ]
        )
    }
}
